name: Build Nuget

on:
  push:
    branches: ['main']
    paths: ['src/**']
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies and build
      run: |
        cd src
        cd NetCoreShortLinksSolution
        dotnet restore
        dotnet build --no-restore
    - name: Build
      run: |
        cd src
        cd NetCoreShortLinksSolution
        dotnet tool restore
        dotnet r pack
    - name: 'Upload nuget'
      #if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/upload-artifact@v2
      with:
        name: NetCoreShortLinksSolution_${{github.run_number}}
        path: src/NetCoreShortLinksSolution/nugetPackages
        retention-days: 1
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
    - name: push to nuget
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
          dotnet nuget push ${{github.workspace}}/src/NetCoreShortLinksSolution/nugetPackages/*symb*.*pkg --api-key  ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json
