name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies and build
      run: |
        cd src
        cd NetCoreShortLinksSolution
        dotnet restore
        dotnet build --no-restore
    - name: Build
      run: |
        cd src
        cd NetCoreShortLinksSolution
        dotnewt tool restore
        dotnet r pack
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
